### ISSUE TITLE
锅巴登录改配置改不了

### ISSUE THREAD

**Issue by Gimme8** [gxy12345/arknights-plugin#10]
因为安装了鸣潮插件所以想改成兼容模式2但是进入锅巴配置里改过了以后点保存没有反应

**Comment by Gimme8** [comment]
点了以后控制台报了这个错
![image](https://github.com/user-attachments/assets/f94e70f7-d8d3-4d58-97f6-59c4a4cfda38)

**Comment by gxy12345** [comment]
> 点了以后控制台报了这个错 ![image](https://private-user-images.githubusercontent.com/112928013/357749648-f94e70f7-d8d3-4d58-97f6-59c4a4cfda38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MzE4ODksIm5iZiI6MTcyMzYzMTU4OSwicGF0aCI6Ii8xMTI5MjgwMTMvMzU3NzQ5NjQ4LWY5NGU3MGY3LWQ4ZDMtNGQ1OC05N2Y2LTU5YzRhNGNmZGEzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQxMDMzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmMxN2M4NDdhZDQxOWE3YjhmNWI1ZjZkMDY2MTViODVjYWZmYzczZjQ3YzZlMmU2YmZhY2FiNWZkMjE3ZmUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aKh496Frt621cNYQKrWZqVy4UibmF1JpNfnFgo2YOMI)

看报错是找不到这个文件了，这个文件不是本插件的文件，应该排查一下该文件所属的插件是否正常

**Comment by Gimme8** [comment]
> > 点了以后控制台报了这个错 ![image](https://private-user-images.githubusercontent.com/112928013/357749648-f94e70f7-d8d3-4d58-97f6-59c4a4cfda38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MzE4ODksIm5iZiI6MTcyMzYzMTU4OSwicGF0aCI6Ii8xMTI5MjgwMTMvMzU3NzQ5NjQ4LWY5NGU3MGY3LWQ4ZDMtNGQ1OC05N2Y2LTU5YzRhNGNmZGEzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQxMDMzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmMxN2M4NDdhZDQxOWE3YjhmNWI1ZjZkMDY2MTViODVjYWZmYzczZjQ3YzZlMmU2YmZhY2FiNWZkMjE3ZmUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aKh496Frt621cNYQKrWZqVy4UibmF1JpNfnFgo2YOMI)
> 
> 看报错是找不到这个文件了，这个文件不是本插件的文件，应该排查一下该文件所属的插件是否正常

没有找到这个插件，而且其他插件能够正常配置，排除了锅巴插件本身可能出错的问题。

> > 点了以后控制台报了这个错 ![image](https://private-user-images.githubusercontent.com/112928013/357749648-f94e70f7-d8d3-4d58-97f6-59c4a4cfda38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MzE4ODksIm5iZiI6MTcyMzYzMTU4OSwicGF0aCI6Ii8xMTI5MjgwMTMvMzU3NzQ5NjQ4LWY5NGU3MGY3LWQ4ZDMtNGQ1OC05N2Y2LTU5YzRhNGNmZGEzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQxMDMzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmMxN2M4NDdhZDQxOWE3YjhmNWI1ZjZkMDY2MTViODVjYWZmYzczZjQ3YzZlMmU2YmZhY2FiNWZkMjE3ZmUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aKh496Frt621cNYQKrWZqVy4UibmF1JpNfnFgo2YOMI)
> 
> 看报错是找不到这个文件了，这个文件不是本插件的文件，应该排查一下该文件所属的插件是否正常



> > 点了以后控制台报了这个错 ![image](https://private-user-images.githubusercontent.com/112928013/357749648-f94e70f7-d8d3-4d58-97f6-59c4a4cfda38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MzE4ODksIm5iZiI6MTcyMzYzMTU4OSwicGF0aCI6Ii8xMTI5MjgwMTMvMzU3NzQ5NjQ4LWY5NGU3MGY3LWQ4ZDMtNGQ1OC05N2Y2LTU5YzRhNGNmZGEzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQxMDMzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmMxN2M4NDdhZDQxOWE3YjhmNWI1ZjZkMDY2MTViODVjYWZmYzczZjQ3YzZlMmU2YmZhY2FiNWZkMjE3ZmUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aKh496Frt621cNYQKrWZqVy4UibmF1JpNfnFgo2YOMI)
> 
> 看报错是找不到这个文件了，这个文件不是本插件的文件，应该排查一下该文件所属的插件是否正常

请问你的能够正常配置吗

**Comment by gxy12345** [comment]
用你图里的文件名搜索了一下，有一个插件有点像，但是好像已经删库了叫脆脆鲨插件(Jinmaocuicuisha-plugin) 。
我在自用的机器人上用锅巴保存是正常的
![QQ_1723633178308](https://github.com/user-attachments/assets/b6da910f-e7ad-4a02-9d9b-4db1d27b5a9e)

**Comment by Gimme8** [comment]
> 用你图里的文件名搜索了一下，有一个插件有点像，但是好像已经删库了叫脆脆鲨插件(Jinmaocuicuisha-plugin) 。 我在自用的机器人上用锅巴保存是正常的 ![QQ_1723633178308](https://private-user-images.githubusercontent.com/13727139/357786069-b6da910f-e7ad-4a02-9d9b-4db1d27b5a9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NzAwODgsIm5iZiI6MTcyMzc2OTc4OCwicGF0aCI6Ii8xMzcyNzEzOS8zNTc3ODYwNjktYjZkYTkxMGYtZTdhZC00YTAyLTlkOWItNGRiMWQyN2I1YTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDAwNTYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2Y2UzZTQ1NDRmMTRlMDE3ODkyMzExZGE4NzRhYWI2ZGNjOWRjYWNiYWRkYmY4ZTMzM2JiNmUzMTQ0MTVkNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fYA1JMKnQQt8dNnRp7ucw3Cj4-RunhkMaFbIamtlIUs)

删了那个插件还是无法保存，看来只能手动修改了，我需要改成兼容模式2（防止和鸣潮插件冲突）请问大佬我需要改哪些配置

**Comment by gxy12345** [comment]
修改arknights-plugin/config/common.yaml，将其中的prefix_mode对应数字改成3

**Comment by Gimme8** [comment]
> 修改arknights-plugin/config/common.yaml，将其中的prefix_mode对应数字改成3，然后重启机器人生效

感谢
