### ISSUE TITLE
token和cred登录都失效

### ISSUE THREAD

**Issue by Gimme8** [gxy12345/arknights-plugin#11]
![屏幕截图 2024-09-04 195813](https://github.com/user-attachments/assets/615d149c-9c6a-498c-adf5-44ce9a6b12dc)

**Comment by Gimme8** [comment]
![image](https://github.com/user-attachments/assets/3c459824-8211-4fde-9ef5-204c7d66c60d)
接口坏了

**Comment by gxy12345** [comment]
像是网络问题，可以尝试多试几次，或者换一个代理试试

**Comment by gxy12345** [comment]
commit:a877be3b26e57a89a2e3e91b07246213deca989f
移除了请求头的connection:close，这可能导致fetch操作时间过长而失败，移除后可以显著减少失败的现象
