### ISSUE TITLE
佬，maa的api应该怎么填写啊

### ISSUE THREAD

**Issue by cj0928** [gxy12345/arknights-plugin#12]
大概是个什么格式

**Comment by gxy12345** [comment]
<img width="612" alt="image" src="https://github.com/user-attachments/assets/cf24f97a-d3ce-4620-a196-3255b84b5674">
这是我的配置，服务是使用[这个](https://github.com/gxy12345/maa_control_api)搭建的，填写部署的机器的IP或是域名+端口，如果嫌麻烦可以直接用图中我搭建的服务

**Comment by gxy12345** [comment]
需要填写的是[API服务](https://github.com/gxy12345/maa_control_api)所部署的host，即协议+域名/IP+端口
我这边有一个公共服务，如果不想折腾可以直接填入使用：http://api.windoge.top:8098
