### ISSUE TITLE
关于命令混淆的问题

### ISSUE THREAD

**Issue by Daroach0** [gxy12345/arknights-plugin#2]
隔壁的明日方舟插件（skland-plugin）的帮助菜单也是用#方舟帮助来唤起的，希望能相互协调一下，做出区分

我因为同时安装了两款插件所以在无论用#方舟帮助还是#方舟插件帮助的时候都只会出现atknights-plugin的帮助菜单所以来这里提出该issue，望知

**Comment by gxy12345** [comment]
在设置项中增加配置项，修改为兼容模式后，#方舟 不再作为前缀匹配

**Comment by molehzy** [comment]
考不考虑弄一个自定义配置，或者默认改成^

![Image](https://github.com/user-attachments/assets/8ad5a216-ffc3-4898-ae71-77fb737ec703)
