### ISSUE TITLE
/便签 的理智和无人及数量于账号的实际情况不符

### ISSUE THREAD

**Issue by yisucheng** [gxy12345/arknights-plugin#3]
多次尝试删除后绑定。token cred两种绑定也都试过仍无法解决，调取时无报错。

**Comment by gxy12345** [comment]
目前森空岛API返回的无人机数量存在更新不及时的问题，误差时间可达1小时。
解决措施：参考[Enhance-for-Skland](https://github.com/LaviniaFalcone/Enhance-for-Skland)项目中的补正措施，可以根据更新时间与当前时间进行近似计算。
```
Math.min(Math.round((Date.now() / 1000 - labor.lastUpdateTime) / 360 + labor.value), labor.maxValue)
```
预计在下次更新中修复

**Comment by gxy12345** [comment]
已优化，不过目前仍有一定误差，暂时没有更好的解决办法
