### ISSUE TITLE
405报错

### ISSUE THREAD

**Issue by Zhuazizizi** [gxy12345/arknights-plugin#4]
执行便签之类的操作或是重获取sk后绑定都会报错，昨天还正常来着
![image](https://github.com/gxy12345/arknights-plugin/assets/107139732/3b615274-c3c3-4702-bd2b-82df006ae59f)
![image](https://github.com/gxy12345/arknights-plugin/assets/107139732/4bcbb212-e731-4d34-8b48-8463f634fbde)

**Comment by gxy12345** [comment]
我无法复现405的问题，可能是网络问题，你可以试着重启一下看看是否可以解决。
报错问题后续会优化一下，这种情况会正确返回错误提示

**Comment by Zhuazizizi** [comment]
> 我无法复现405的问题，可能是网络问题，你可以试着重启一下看看是否可以解决。
> 报错问题后续会优化一下，这种情况会正确返回错误提示

似乎。服务器ip被拉黑了？试了下别的方舟插件也不能用。通过挂代理改ip的方式好像才能用
