### ISSUE TITLE
cerd一直说绑定失败

### ISSUE THREAD

**Issue by hxwd94666** [gxy12345/arknights-plugin#6]
根据cerd帮助获取的cerd和token发过去都报错，说“绑定失败，请检查cerd”，另外给机器人发/cerd帮助没有反应

**Comment by gxy12345** [comment]
提供一下后台日志，如果"/"前缀的命令无效，可以试一下“~”做前缀

**Comment by hxwd94666** [comment]
这些前缀都没效果，然后cerd的绑定后台接口报错

**Comment by hxwd94666** [comment]
![Uploading Image_1717563492615.jpg…]()

**Comment by hxwd94666** [comment]
![OYQEC)_75OP$NC6)0@H%GT7](https://github.com/gxy12345/arknights-plugin/assets/111326771/c088c77e-6f74-4e3c-bc7b-d43d8cfabb01)

**Comment by hxwd94666** [comment]
![$A}B$2}~6`$LPPK}GMQO8F1](https://github.com/gxy12345/arknights-plugin/assets/111326771/4f3787e0-ad22-4a60-a1e9-f6f8d38ff951)

**Comment by gxy12345** [comment]
1. 405错误，大概率是IP被森空岛ban了，参考 #4 可以挂代理解决
2. 命令无效，是命令写错了，是cred而不是cerd
