### ISSUE TITLE
方舟理智获取问题

### ISSUE THREAD

**Issue by AEDELSTAN** [gxy12345/arknights-plugin#8]
我绑定的是token，但是除了第一次是正确的以外，之后都是 【理智: 26/133】  似乎不会更新。请问作者有遇到这个情况吗？

补充：有尝试过重绑token，未尝试绑定cred

**Comment by gxy12345** [comment]
可以查看一下`/便签` 命令里面的理智是否有更新，之前修改计算逻辑时漏了`/理智`这个命令了，后续会修复
