### ISSUE TITLE
希望触发前缀可以自定义

### ISSUE THREAD

**Issue by QianYeXingChen** [gxy12345/arknights-plugin#9]
本插件的~触发前缀和鸣潮插件有冲突不知道能否解决，谢谢。

**Comment by gxy12345** [comment]
由于一些功能依赖正则匹配的格式，如果开放自定义可能产生难以预估的问题。目前增加了一个应对鸣潮插件的兼容模式2，在完整的基础上去掉了“~”的前缀匹配。可以在锅巴设置里面更改
<img width="837" alt="image" src="https://github.com/gxy12345/arknights-plugin/assets/13727139/99c82db5-7f72-4c52-8d96-721e16db7e42">
